services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - app
    container_name: payment_system_nginx
    networks:
      - payment_network

  app:
    image: php-nodejs
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: payment_system_app
    depends_on:
      - db
      - redis
    ports:
      - "5173:5173"
    networks:
      - payment_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment-app.rule=Host(`${IP}.sslip.io`)"
      - "traefik.http.routers.payment-app.entrypoints=websecure"
      - "traefik.http.routers.payment-app.tls=true"
      - "traefik.http.routers.payment-app.tls.certresolver=myresolver"
      # Указываем порт, который слушает твой Nginx внутри контейнера (обычно 80)
      - "traefik.http.services.payment-app.loadbalancer.server.port=${NGINX_PORT}"

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
        - ./tmp/db:/var/lib/postgresql/18/docker
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command:
      - "postgres"
      - "-c"
      - 'port=${DB_PORT}'
    container_name: payment_system_db
    networks:
      - payment_network
  traefik:
    image: traefik:v3.0
    container_name: payment_system_traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Открываем порты для HTTP и HTTPS
      - "--entrypoints.web.address=:${NGINX_PORT}"
      - "--entrypoints.websecure.address=:443"
      # Настройка автоматического редиректа с HTTP на HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Конфигурация Let's Encrypt (ACME)
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "${NGINX_POST}:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Чтобы Traefik видел другие контейнеры
      - traefik_certs:/letsencrypt
    networks:
      - payment_network

  supervisor_worker:
    image: php-nodejs
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    command: [ "/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
    container_name: payment_system_supervisor_worker
    networks:
      - payment_network

  redis:
    image: redis:8.10-alpine
    container_name: payment_system_redis
    restart: unless-stopped
    command: >
      redis-server
      --requirepass "${REDIS_PASSWORD}"
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    ports:
      - "127.0.0.1:${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - payment_redis_data:/data
    networks:
      payment_network:
        aliases:
          - payment_system_redis

volumes:
  traefik_certs:
  payment_redis_data:
    driver: local

networks:
  payment_network:
    driver: bridge
