[supervisord]
nodaemon=true               ; Удерживает процесс на переднем плане (важно для Docker)
pidfile=/tmp/supervisord.pid
logfile=/dev/stdout         ; Пробрасываем логи в консоль Docker
logfile_maxbytes=0          ; Отключаем ротацию для stdout

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true              ; Запускать при старте контейнера
autorestart=true            ; Перезапускать, если процесс упал
stopasgroup=true            ; Останавливать всю группу процессов
killasgroup=true            ; Принудительно убивать группу при выходе
user=www-data               ; Юзер, от которого крутится код
numprocs=2                  ; Сколько параллельных воркеров запустить
stdout_logfile=/dev/stdout  ; Логи воркера в стандартный вывод
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr  ; Ошибки воркера в вывод ошибок
stderr_logfile_maxbytes=0
